
/* ####################################################### RANDOM INSERTS */

/* ####################################################### technology */

INSERT INTO technology (tech_name) VALUES ('PHP');
INSERT INTO technology (tech_name) VALUES ('JavaScript');
INSERT INTO technology (tech_name) VALUES ('Java');
INSERT INTO technology (tech_name) VALUES ('Python');
INSERT INTO technology (tech_name) VALUES ('Swift');
INSERT INTO technology (tech_name) VALUES ('Ruby');
INSERT INTO technology (tech_name) VALUES ('C++');
INSERT INTO technology (tech_name) VALUES ('C#');
INSERT INTO technology (tech_name) VALUES ('C');
INSERT INTO technology (tech_name) VALUES ('Visual Basic');
INSERT INTO technology (tech_name) VALUES ('Perl');
INSERT INTO technology (tech_name) VALUES ('CSS');
INSERT INTO technology (tech_name) VALUES ('HTML');
INSERT INTO technology (tech_name) VALUES ('Angular');
INSERT INTO technology (tech_name) VALUES ('Django');
INSERT INTO technology (tech_name) VALUES ('Spring');
INSERT INTO technology (tech_name) VALUES ('Yii');
INSERT INTO technology (tech_name) VALUES ('Zend Framework');
INSERT INTO technology (tech_name) VALUES ('Symfony');
INSERT INTO technology (tech_name) VALUES ('ReactJS');
INSERT INTO technology (tech_name) VALUES ('Bootstrap');
INSERT INTO technology (tech_name) VALUES ('Objetive-C');
INSERT INTO technology (tech_name) VALUES ('Pascal');
INSERT INTO technology (tech_name) VALUES ('Go');
INSERT INTO technology (tech_name) VALUES ('Scala');
INSERT INTO technology (tech_name) VALUES ('Rust');
INSERT INTO technology (tech_name) VALUES ('Ruby on rails');
INSERT INTO technology (tech_name) VALUES ('Laravel');
INSERT INTO technology (tech_name) VALUES ('Node JS');

/* ####################################################### search_tech */

INSERT INTO search_tech (id_search, preference, id_technology) VALUES (1, 1, 4);
INSERT INTO search_tech (id_search, preference, id_technology) VALUES (1, 2, 27);
INSERT INTO search_tech (id_search, preference, id_technology) VALUES (1, 3, 9);
INSERT INTO search_tech (id_search, preference, id_technology) VALUES (1, 4, 3);
INSERT INTO search_tech (id_search, preference, id_technology) VALUES (1, 5, 25);
INSERT INTO search_tech (id_search, preference, id_technology) VALUES (1, 6, 21);
INSERT INTO search_tech (id_search, preference, id_technology) VALUES (1, 7, 2);
INSERT INTO search_tech (id_search, preference, id_technology) VALUES (1, 8, 15);
INSERT INTO search_tech (id_search, preference, id_technology) VALUES (1, 9, 12);

/* ####################################################### developer */

INSERT INTO developer (alias) VALUES ('metusetlaoreet');
INSERT INTO developer (alias) VALUES ('rhoncusduiluctus');
INSERT INTO developer (alias) VALUES ('ligulaodiomaecenas');
INSERT INTO developer (alias) VALUES ('nonligularisus');
INSERT INTO developer (alias) VALUES ('antelacusdui');
INSERT INTO developer (alias) VALUES ('quisquehendreritlaoreet');
INSERT INTO developer (alias) VALUES ('classvariuslitora');
INSERT INTO developer (alias) VALUES ('ornarehendreritlitora');
INSERT INTO developer (alias) VALUES ('condimentumlectusconvallis');
INSERT INTO developer (alias) VALUES ('idneceuismod');
INSERT INTO developer (alias) VALUES ('massarhoncussociis');
INSERT INTO developer (alias) VALUES ('blanditerathac');
INSERT INTO developer (alias) VALUES ('bibendumporttitorhac');
INSERT INTO developer (alias) VALUES ('acrasfaucibus');
INSERT INTO developer (alias) VALUES ('magnaconvallishimenaeos');
INSERT INTO developer (alias) VALUES ('cursuspellentesquevenenatis');
INSERT INTO developer (alias) VALUES ('magnanisialiquam');
INSERT INTO developer (alias) VALUES ('condimentumpellentesquesodales');
INSERT INTO developer (alias) VALUES ('suspendissevariushabitasse');
INSERT INTO developer (alias) VALUES ('dapibusfermentumin');
INSERT INTO developer (alias) VALUES ('quissemat');
INSERT INTO developer (alias) VALUES ('potentidictumfaucibus');
INSERT INTO developer (alias) VALUES ('curaenuncscelerisque');
INSERT INTO developer (alias) VALUES ('volutpatridiculusdictum');
INSERT INTO developer (alias) VALUES ('conguesuscipitrhoncus');
INSERT INTO developer (alias) VALUES ('pharetraatvenenatis');
INSERT INTO developer (alias) VALUES ('inprimismalesuada');
INSERT INTO developer (alias) VALUES ('suspendisseenimtincidunt');
INSERT INTO developer (alias) VALUES ('aliquetvelpurus');
INSERT INTO developer (alias) VALUES ('pharetramaurismolestie');
INSERT INTO developer (alias) VALUES ('nostraaliquamnulla');
INSERT INTO developer (alias) VALUES ('nullamrhoncuslacinia');
INSERT INTO developer (alias) VALUES ('pulvinarcurabiturfacilisi');
INSERT INTO developer (alias) VALUES ('discongueaenean');
INSERT INTO developer (alias) VALUES ('convallisridiculusvel');
INSERT INTO developer (alias) VALUES ('velitegetmorbi');
INSERT INTO developer (alias) VALUES ('accumsandonecluctus');
INSERT INTO developer (alias) VALUES ('quisquemagnisrutrum');
INSERT INTO developer (alias) VALUES ('netuspotentiproin');
INSERT INTO developer (alias) VALUES ('conguemaecenasvarius');
INSERT INTO developer (alias) VALUES ('odiobibendumhabitant');
INSERT INTO developer (alias) VALUES ('dictumsenectuscurae');
INSERT INTO developer (alias) VALUES ('proincubiliamauris');
INSERT INTO developer (alias) VALUES ('admolestiepretium');
INSERT INTO developer (alias) VALUES ('gravidaaeneanaenean');
INSERT INTO developer (alias) VALUES ('rutrumpurussollicitudin');
INSERT INTO developer (alias) VALUES ('scelerisqueportalacinia');
INSERT INTO developer (alias) VALUES ('auctorlacusridiculus');
INSERT INTO developer (alias) VALUES ('dictumstnamet');
INSERT INTO developer (alias) VALUES ('velitultricessenectus');
INSERT INTO developer (alias) VALUES ('ultricesportafacilisi');
INSERT INTO developer (alias) VALUES ('morbiintegerneque');
INSERT INTO developer (alias) VALUES ('facilisisociosqucurae');
INSERT INTO developer (alias) VALUES ('euismodelementumnascetur');
INSERT INTO developer (alias) VALUES ('disdonecinceptos');
INSERT INTO developer (alias) VALUES ('felisperridiculus');
INSERT INTO developer (alias) VALUES ('purusmagnavolutpat');
INSERT INTO developer (alias) VALUES ('aliquetfaucibushabitant');
INSERT INTO developer (alias) VALUES ('mollisdonecprimis');
INSERT INTO developer (alias) VALUES ('senectuscubiliaquisque');
INSERT INTO developer (alias) VALUES ('praesentrisustaciti');
INSERT INTO developer (alias) VALUES ('enimarcudui');
INSERT INTO developer (alias) VALUES ('namiddiam');
INSERT INTO developer (alias) VALUES ('lobortislitoravivamus');
INSERT INTO developer (alias) VALUES ('suspendissescelerisquejusto');
INSERT INTO developer (alias) VALUES ('acrutrumac');
INSERT INTO developer (alias) VALUES ('gravidaacest');
INSERT INTO developer (alias) VALUES ('auguedispenatibus');
INSERT INTO developer (alias) VALUES ('prointortorrhoncus');
INSERT INTO developer (alias) VALUES ('euismodetiamultrices');
INSERT INTO developer (alias) VALUES ('placeratfuscedonec');
INSERT INTO developer (alias) VALUES ('gravidafacilisinatoque');
INSERT INTO developer (alias) VALUES ('ornareeratfaucibus');
INSERT INTO developer (alias) VALUES ('sociosquiaculisiaculis');
INSERT INTO developer (alias) VALUES ('maurisnisldictum');
INSERT INTO developer (alias) VALUES ('urnanisinatoque');
INSERT INTO developer (alias) VALUES ('mifermentumid');
INSERT INTO developer (alias) VALUES ('hacauguetorquent');
INSERT INTO developer (alias) VALUES ('commodoantevelit');
INSERT INTO developer (alias) VALUES ('facilisivitaepulvinar');
INSERT INTO developer (alias) VALUES ('lacustortoregestas');
INSERT INTO developer (alias) VALUES ('etiamsapieneu');
INSERT INTO developer (alias) VALUES ('primisinclass');
INSERT INTO developer (alias) VALUES ('rutrumclassac');
INSERT INTO developer (alias) VALUES ('cubiliamaecenasplatea');
INSERT INTO developer (alias) VALUES ('vitaeelementumligula');
INSERT INTO developer (alias) VALUES ('duisetiaminceptos');
INSERT INTO developer (alias) VALUES ('idmaecenascubilia');
INSERT INTO developer (alias) VALUES ('senectusimperdietproin');
INSERT INTO developer (alias) VALUES ('temporsapieneu');
INSERT INTO developer (alias) VALUES ('commodovolutpatmagnis');
INSERT INTO developer (alias) VALUES ('lobortiscondimentumposuere');
INSERT INTO developer (alias) VALUES ('vitaemolestienon');
INSERT INTO developer (alias) VALUES ('egetlitoraaliquet');
INSERT INTO developer (alias) VALUES ('atutenim');
INSERT INTO developer (alias) VALUES ('nullanisiporttitor');
INSERT INTO developer (alias) VALUES ('eratconsequatlaoreet');
INSERT INTO developer (alias) VALUES ('morbiquisqueenim');
INSERT INTO developer (alias) VALUES ('fusceinceptosmollis');
INSERT INTO developer (alias) VALUES ('velitcrasblandit');

/* ####################################################### developer_tech */

INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (1, 12, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (1, 11, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (1, 13, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (1, 7, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (1, 25, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (1, 2, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (1, 3, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (1, 21, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (1, 19, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (1, 14, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (1, 18, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (1, 10, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (2, 24, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (2, 5, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (2, 20, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (2, 15, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (2, 12, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (3, 18, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (3, 5, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (3, 22, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (4, 6, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (4, 5, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (4, 15, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (4, 10, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (4, 29, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (4, 21, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (4, 20, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (4, 3, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (4, 22, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (4, 26, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (5, 28, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (5, 19, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (6, 9, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (6, 10, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (6, 15, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (6, 8, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (6, 3, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (6, 27, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (6, 26, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (6, 11, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (6, 4, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (6, 6, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (6, 13, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (6, 23, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (7, 3, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (7, 1, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (8, 17, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (8, 12, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (8, 6, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (8, 1, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (8, 28, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (8, 29, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (8, 24, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (8, 20, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (8, 2, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (8, 18, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (8, 19, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (8, 22, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (9, 4, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (9, 13, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (9, 25, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (9, 29, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (9, 20, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (9, 21, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (9, 15, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (10, 22, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (10, 3, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (10, 13, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (10, 18, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (10, 7, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (11, 18, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (11, 24, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (11, 12, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (11, 8, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (11, 22, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (11, 16, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (11, 28, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (11, 14, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (12, 13, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (12, 11, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (12, 26, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (12, 8, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (13, 21, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (13, 12, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (13, 1, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (13, 27, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (14, 17, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (15, 12, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (15, 10, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (15, 26, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (15, 22, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (15, 28, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (15, 8, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (15, 24, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (15, 18, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (16, 13, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (16, 15, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (16, 25, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (16, 2, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (17, 28, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (17, 25, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (17, 2, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (17, 4, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (17, 1, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (17, 16, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (18, 16, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (19, 16, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (19, 19, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (19, 5, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (19, 7, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (19, 1, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (19, 18, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (19, 23, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (19, 24, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (19, 29, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (19, 28, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (19, 13, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (19, 15, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (20, 25, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (20, 6, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (20, 12, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (20, 16, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (20, 7, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (20, 2, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (20, 14, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (20, 4, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (21, 4, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (21, 15, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (21, 23, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (21, 2, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (21, 22, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (21, 12, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (21, 18, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (21, 8, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (21, 26, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (21, 5, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (22, 4, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (22, 5, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (23, 29, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (23, 3, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (23, 16, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (23, 7, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (23, 21, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (23, 27, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (23, 19, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (23, 18, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (23, 4, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (23, 24, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (23, 15, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (24, 19, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (24, 4, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (24, 17, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (24, 27, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (24, 18, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (24, 21, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (24, 24, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (24, 10, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (25, 8, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (25, 12, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (25, 26, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (25, 11, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (25, 15, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (25, 16, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (25, 9, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (25, 4, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (25, 5, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (25, 1, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (26, 17, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (26, 12, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (26, 28, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (27, 7, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (27, 1, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (28, 20, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (28, 29, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (28, 2, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (28, 8, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (28, 28, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (28, 9, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (28, 5, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (28, 22, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (29, 9, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (29, 24, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (29, 6, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (30, 20, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (30, 5, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (30, 1, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (30, 6, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (30, 19, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (30, 4, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (30, 8, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (30, 15, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (30, 16, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (30, 22, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (30, 29, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (30, 17, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (31, 28, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (31, 23, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (31, 2, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (31, 17, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (32, 4, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (32, 23, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (32, 20, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (32, 6, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (32, 1, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (32, 8, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (32, 14, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (32, 2, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (32, 21, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (32, 17, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (32, 22, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (32, 5, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (33, 12, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (34, 25, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (34, 23, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (34, 6, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (34, 13, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (34, 10, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (34, 15, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (34, 18, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (34, 4, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (34, 7, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (35, 21, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (35, 13, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (35, 26, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (35, 1, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (36, 8, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (36, 3, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (36, 27, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (36, 14, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (36, 28, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (37, 25, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (37, 16, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (37, 8, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (37, 19, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (37, 7, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (37, 13, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (37, 3, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (38, 24, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (38, 12, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (38, 11, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (38, 26, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (38, 21, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (38, 16, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (38, 28, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (39, 27, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (40, 15, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (40, 1, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (40, 11, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (40, 21, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (40, 6, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (40, 7, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (40, 27, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (40, 12, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (41, 27, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (41, 10, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (41, 2, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (41, 1, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (41, 19, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (41, 16, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (42, 17, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (42, 21, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (43, 7, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (43, 6, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (43, 25, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (43, 12, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (43, 22, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (43, 14, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (43, 13, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (43, 5, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (43, 26, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (44, 15, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (44, 14, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (44, 2, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (44, 29, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (44, 19, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (44, 9, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (44, 4, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (44, 5, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (44, 8, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (45, 3, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (45, 8, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (45, 26, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (45, 12, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (45, 15, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (45, 14, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (45, 22, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (45, 20, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (46, 9, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (47, 18, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (47, 28, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (47, 19, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (47, 17, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (47, 25, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (47, 26, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (47, 15, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (47, 2, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (47, 13, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (47, 1, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (48, 15, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (48, 12, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (48, 24, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (48, 10, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (48, 4, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (49, 26, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (49, 13, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (49, 11, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (49, 18, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (50, 7, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (50, 1, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (50, 17, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (50, 8, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (50, 27, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (51, 24, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (51, 28, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (51, 29, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (51, 5, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (51, 2, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (51, 11, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (51, 1, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (52, 20, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (52, 23, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (52, 19, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (52, 10, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (52, 4, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (52, 14, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (52, 29, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (52, 26, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (52, 15, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (52, 11, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (53, 10, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (53, 3, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (53, 16, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (53, 26, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (53, 15, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (53, 13, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (53, 11, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (53, 12, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (53, 14, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (53, 1, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (54, 20, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (54, 4, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (54, 15, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (54, 23, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (54, 6, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (54, 2, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (54, 18, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (55, 27, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (55, 7, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (56, 20, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (56, 5, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (56, 9, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (56, 10, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (57, 5, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (57, 2, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (58, 26, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (58, 8, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (58, 29, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (58, 13, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (58, 2, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (58, 7, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (58, 3, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (59, 11, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (59, 17, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (59, 15, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (59, 24, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (59, 13, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (59, 14, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (59, 8, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (59, 28, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (59, 27, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (59, 6, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (59, 7, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (59, 2, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (60, 12, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (60, 6, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (60, 20, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (60, 1, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (60, 13, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (60, 8, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (61, 12, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (61, 6, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (61, 9, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (61, 17, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (62, 16, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (62, 4, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (62, 23, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (62, 24, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (62, 27, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (62, 9, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (63, 8, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (63, 27, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (63, 13, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (63, 16, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (63, 25, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (63, 6, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (63, 15, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (63, 17, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (63, 11, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (64, 26, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (64, 14, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (64, 23, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (64, 12, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (64, 7, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (64, 25, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (64, 16, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (65, 29, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (65, 23, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (66, 4, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (66, 18, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (66, 16, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (66, 29, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (66, 26, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (66, 28, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (66, 21, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (66, 8, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (66, 5, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (66, 7, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (67, 6, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (67, 8, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (67, 21, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (67, 22, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (67, 10, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (67, 15, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (67, 9, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (67, 28, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (67, 24, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (67, 25, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (67, 1, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (68, 14, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (68, 2, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (69, 7, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (69, 6, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (69, 23, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (69, 22, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (69, 26, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (69, 9, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (70, 3, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (70, 5, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (70, 24, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (70, 2, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (70, 6, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (71, 28, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (71, 14, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (71, 3, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (71, 22, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (71, 21, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (71, 26, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (71, 19, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (72, 4, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (72, 21, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (72, 26, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (72, 16, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (72, 20, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (72, 14, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (72, 19, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (73, 13, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (73, 24, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (73, 1, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (73, 2, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (73, 29, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (73, 5, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (73, 15, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (73, 7, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (74, 15, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (74, 21, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (74, 10, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (75, 15, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (75, 18, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (76, 8, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (76, 21, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (76, 20, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (76, 19, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (76, 1, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (76, 12, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (76, 25, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (76, 2, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (77, 21, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (77, 4, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (77, 7, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (77, 17, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (77, 16, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (77, 26, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (77, 27, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (77, 28, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (77, 12, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (78, 14, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (78, 18, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (78, 15, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (78, 10, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (78, 24, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (78, 25, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (78, 22, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (78, 8, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (78, 21, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (78, 23, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (78, 19, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (78, 2, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (79, 11, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (80, 19, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (80, 2, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (80, 4, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (80, 22, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (80, 3, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (81, 14, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (81, 8, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (81, 27, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (81, 2, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (81, 13, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (81, 10, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (81, 24, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (81, 19, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (81, 6, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (81, 4, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (82, 22, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (83, 16, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (83, 9, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (83, 13, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (83, 6, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (83, 14, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (83, 11, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (83, 3, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (83, 20, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (84, 27, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (84, 26, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (84, 12, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (85, 17, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (85, 1, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (85, 3, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (86, 28, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (86, 22, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (86, 24, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (86, 13, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (87, 10, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (88, 17, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (88, 29, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (88, 8, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (88, 11, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (89, 10, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (89, 3, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (89, 6, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (89, 16, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (89, 5, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (89, 23, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (89, 24, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (90, 24, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (90, 5, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (90, 23, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (90, 3, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (90, 6, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (90, 26, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (91, 2, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (91, 6, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (91, 1, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (91, 23, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (91, 26, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (91, 28, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (91, 17, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (91, 14, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (91, 8, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (91, 7, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (92, 25, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (92, 17, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (92, 26, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (93, 28, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (93, 12, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (93, 25, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (93, 9, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (93, 1, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (93, 21, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (93, 10, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (93, 22, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (94, 4, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (94, 8, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (94, 11, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (94, 9, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (94, 15, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (94, 1, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (94, 7, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (94, 21, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (94, 24, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (94, 12, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (94, 19, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (94, 14, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (95, 9, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (96, 18, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (96, 29, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (96, 4, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (96, 23, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (96, 11, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (96, 22, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (97, 25, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (97, 22, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (97, 13, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (97, 5, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (97, 7, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (98, 22, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (98, 1, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (98, 26, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (98, 19, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (98, 4, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (98, 29, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (98, 14, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (98, 16, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (98, 3, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (99, 5, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (99, 2, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (99, 9, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (99, 15, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (99, 21, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (99, 23, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (99, 17, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (99, 19, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (100, 11, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (100, 10, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (100, 28, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (100, 4, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (100, 17, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (100, 1, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (100, 8, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (100, 25, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (100, 24, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (100, 12, 2);
