<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ0i4ea9\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ0i4ea9/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ0i4ea9.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ0i4ea9\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQ0i4ea9\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Q0i4ea9',
    'container.build_id' => '7cfb47df',
    'container.build_time' => 1551523543,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ0i4ea9');
