<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX9ZY2NP\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX9ZY2NP/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX9ZY2NP.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX9ZY2NP\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerX9ZY2NP\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'X9ZY2NP',
    'container.build_id' => 'f5502a84',
    'container.build_time' => 1551813806,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX9ZY2NP');
