<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUX2HpKj\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUX2HpKj/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUX2HpKj.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUX2HpKj\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUX2HpKj\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UX2HpKj',
    'container.build_id' => '581e8882',
    'container.build_time' => 1552066265,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUX2HpKj');
