<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF4FD3Ao\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF4FD3Ao/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF4FD3Ao.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF4FD3Ao\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerF4FD3Ao\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'F4FD3Ao',
    'container.build_id' => '62a91fe3',
    'container.build_time' => 1552399899,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF4FD3Ao');
