
/* ####################################################### RANDOM INSERTS */


/* ####################################################### technology */

INSERT INTO technology (tech_name) VALUES ('PHP');
INSERT INTO technology (tech_name) VALUES ('JavaScript');
INSERT INTO technology (tech_name) VALUES ('Java');
INSERT INTO technology (tech_name) VALUES ('Python');
INSERT INTO technology (tech_name) VALUES ('Swift');
INSERT INTO technology (tech_name) VALUES ('Ruby');
INSERT INTO technology (tech_name) VALUES ('C++');
INSERT INTO technology (tech_name) VALUES ('C#');
INSERT INTO technology (tech_name) VALUES ('C');
INSERT INTO technology (tech_name) VALUES ('Visual Basic');
INSERT INTO technology (tech_name) VALUES ('Perl');
INSERT INTO technology (tech_name) VALUES ('CSS');
INSERT INTO technology (tech_name) VALUES ('HTML');
INSERT INTO technology (tech_name) VALUES ('Angular');
INSERT INTO technology (tech_name) VALUES ('Django');
INSERT INTO technology (tech_name) VALUES ('Spring');
INSERT INTO technology (tech_name) VALUES ('Yii');
INSERT INTO technology (tech_name) VALUES ('Zend Framework');
INSERT INTO technology (tech_name) VALUES ('Symfony');
INSERT INTO technology (tech_name) VALUES ('ReactJS');
INSERT INTO technology (tech_name) VALUES ('Bootstrap');
INSERT INTO technology (tech_name) VALUES ('Objetive-C');
INSERT INTO technology (tech_name) VALUES ('Pascal');
INSERT INTO technology (tech_name) VALUES ('Go');
INSERT INTO technology (tech_name) VALUES ('Scala');
INSERT INTO technology (tech_name) VALUES ('Rust');
INSERT INTO technology (tech_name) VALUES ('Ruby on rails');
INSERT INTO technology (tech_name) VALUES ('Laravel');
INSERT INTO technology (tech_name) VALUES ('Node JS');

/* ####################################################### search_tech */

INSERT INTO search_tech (id_search, preference, id_technology) VALUES (1, 1, 3);
INSERT INTO search_tech (id_search, preference, id_technology) VALUES (1, 2, 26);
INSERT INTO search_tech (id_search, preference, id_technology) VALUES (1, 3, 27);

/* ####################################################### developer */

INSERT INTO developer (alias) VALUES ('quisquedictumporta');
INSERT INTO developer (alias) VALUES ('accumsannequesagittis');
INSERT INTO developer (alias) VALUES ('rhoncusrutruminterdum');
INSERT INTO developer (alias) VALUES ('sedbibendummalesuada');
INSERT INTO developer (alias) VALUES ('dictumpraesentrutrum');
INSERT INTO developer (alias) VALUES ('ultricesconsequatfames');
INSERT INTO developer (alias) VALUES ('magnisaccumsanpharetra');
INSERT INTO developer (alias) VALUES ('mattisposuerecommodo');
INSERT INTO developer (alias) VALUES ('mollismusquisque');
INSERT INTO developer (alias) VALUES ('torquentmolestievolutpat');
INSERT INTO developer (alias) VALUES ('semduiullamcorper');
INSERT INTO developer (alias) VALUES ('aptentinceptosrisus');
INSERT INTO developer (alias) VALUES ('interdumliberovivamus');
INSERT INTO developer (alias) VALUES ('magnisporttitorsollicitudin');
INSERT INTO developer (alias) VALUES ('tortoreleifendmetus');
INSERT INTO developer (alias) VALUES ('praesenteudictum');
INSERT INTO developer (alias) VALUES ('facilisiconvallisiaculis');
INSERT INTO developer (alias) VALUES ('facilisivulputategravida');
INSERT INTO developer (alias) VALUES ('facilisicumpulvinar');
INSERT INTO developer (alias) VALUES ('morbimalesuadamassa');
INSERT INTO developer (alias) VALUES ('tempusconubianon');
INSERT INTO developer (alias) VALUES ('eleifendmetussociis');
INSERT INTO developer (alias) VALUES ('tempusinmollis');
INSERT INTO developer (alias) VALUES ('perpulvinarpurus');
INSERT INTO developer (alias) VALUES ('felisgravidacommodo');
INSERT INTO developer (alias) VALUES ('velitscelerisquecommodo');
INSERT INTO developer (alias) VALUES ('vitaevelcursus');
INSERT INTO developer (alias) VALUES ('orcirhoncusconubia');
INSERT INTO developer (alias) VALUES ('habitantadac');
INSERT INTO developer (alias) VALUES ('scelerisquetortormetus');
INSERT INTO developer (alias) VALUES ('duislitoramattis');
INSERT INTO developer (alias) VALUES ('tempusplateanostra');
INSERT INTO developer (alias) VALUES ('fuscerutrumrisus');
INSERT INTO developer (alias) VALUES ('donecnonhimenaeos');
INSERT INTO developer (alias) VALUES ('orcivehiculalobortis');
INSERT INTO developer (alias) VALUES ('suspendisseetiamimperdiet');
INSERT INTO developer (alias) VALUES ('viverravestibulummi');
INSERT INTO developer (alias) VALUES ('nonmagnanec');
INSERT INTO developer (alias) VALUES ('natoquesenectusante');
INSERT INTO developer (alias) VALUES ('necmagnaaptent');
INSERT INTO developer (alias) VALUES ('mollispretiumcras');
INSERT INTO developer (alias) VALUES ('inceptosaccumsaniaculis');
INSERT INTO developer (alias) VALUES ('famesdignissimerat');
INSERT INTO developer (alias) VALUES ('egetlaoreethabitasse');
INSERT INTO developer (alias) VALUES ('cumsociismaecenas');
INSERT INTO developer (alias) VALUES ('habitantorcimorbi');
INSERT INTO developer (alias) VALUES ('maurismorbiultrices');
INSERT INTO developer (alias) VALUES ('velmivarius');
INSERT INTO developer (alias) VALUES ('nequevivamusgravida');
INSERT INTO developer (alias) VALUES ('nisldiamvitae');
INSERT INTO developer (alias) VALUES ('accumsanhendreritmassa');
INSERT INTO developer (alias) VALUES ('lectushabitassenibh');
INSERT INTO developer (alias) VALUES ('dapibusconvalliscras');
INSERT INTO developer (alias) VALUES ('potentipenatibuscursus');
INSERT INTO developer (alias) VALUES ('massaetiamcursus');
INSERT INTO developer (alias) VALUES ('sociosquduilitora');
INSERT INTO developer (alias) VALUES ('perplaceratelementum');
INSERT INTO developer (alias) VALUES ('ornareintegersuspendisse');
INSERT INTO developer (alias) VALUES ('miullamcorpertorquent');
INSERT INTO developer (alias) VALUES ('curaelaoreetornare');
INSERT INTO developer (alias) VALUES ('portaegestastaciti');
INSERT INTO developer (alias) VALUES ('dignissimsociosqualiquet');
INSERT INTO developer (alias) VALUES ('netusestelementum');
INSERT INTO developer (alias) VALUES ('urnaquisquepurus');
INSERT INTO developer (alias) VALUES ('ultriciesdictumvivamus');
INSERT INTO developer (alias) VALUES ('esteuismodpharetra');
INSERT INTO developer (alias) VALUES ('sagittismusquisque');
INSERT INTO developer (alias) VALUES ('suspendissecrasmattis');
INSERT INTO developer (alias) VALUES ('parturientaeneanphasellus');
INSERT INTO developer (alias) VALUES ('fringillavolutpateros');
INSERT INTO developer (alias) VALUES ('donecfeugiatrhoncus');
INSERT INTO developer (alias) VALUES ('faucibusvelitneque');
INSERT INTO developer (alias) VALUES ('quisquetempussuscipit');
INSERT INTO developer (alias) VALUES ('sociishacmolestie');
INSERT INTO developer (alias) VALUES ('antegravidaaenean');
INSERT INTO developer (alias) VALUES ('duisuspendisselobortis');
INSERT INTO developer (alias) VALUES ('dapibusfacilisishabitasse');
INSERT INTO developer (alias) VALUES ('facilisiquisid');
INSERT INTO developer (alias) VALUES ('mattiscurabiturridiculus');
INSERT INTO developer (alias) VALUES ('faucibusegetpellentesque');
INSERT INTO developer (alias) VALUES ('conubiahacvitae');
INSERT INTO developer (alias) VALUES ('interdumtelluseleifend');
INSERT INTO developer (alias) VALUES ('eleifendmattismetus');
INSERT INTO developer (alias) VALUES ('lobortissuscipitcum');
INSERT INTO developer (alias) VALUES ('euismodparturienterat');
INSERT INTO developer (alias) VALUES ('habitantnecsuscipit');
INSERT INTO developer (alias) VALUES ('cumetneque');
INSERT INTO developer (alias) VALUES ('estlectusnetus');
INSERT INTO developer (alias) VALUES ('morbiviverraquam');
INSERT INTO developer (alias) VALUES ('netusegestasnibh');
INSERT INTO developer (alias) VALUES ('porttitorcurabiturscelerisque');
INSERT INTO developer (alias) VALUES ('ullamcorperintegercubilia');
INSERT INTO developer (alias) VALUES ('himenaeossodalesvitae');
INSERT INTO developer (alias) VALUES ('pharetramaecenasarcu');
INSERT INTO developer (alias) VALUES ('portacommodoorci');
INSERT INTO developer (alias) VALUES ('suspendissecuraepretium');
INSERT INTO developer (alias) VALUES ('cursusquameros');
INSERT INTO developer (alias) VALUES ('odiovehiculafelis');
INSERT INTO developer (alias) VALUES ('adplateaimperdiet');
INSERT INTO developer (alias) VALUES ('laoreetrutrumneque');

/* ####################################################### developer_tech */

INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (1, 7, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (1, 21, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (1, 2, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (1, 22, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (1, 3, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (2, 18, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (3, 16, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (3, 10, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (3, 8, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (3, 22, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (3, 17, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (4, 1, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (4, 27, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (4, 9, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (5, 4, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (5, 18, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (5, 26, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (5, 17, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (6, 7, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (6, 26, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (7, 13, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (7, 26, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (7, 1, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (8, 9, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (8, 22, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (8, 5, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (8, 29, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (9, 17, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (10, 14, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (10, 2, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (10, 11, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (10, 12, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (11, 20, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (12, 24, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (12, 28, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (12, 5, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (12, 3, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (12, 2, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (13, 13, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (13, 4, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (13, 25, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (13, 11, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (14, 17, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (14, 22, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (15, 13, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (15, 26, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (15, 12, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (15, 3, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (15, 27, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (16, 13, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (16, 2, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (16, 14, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (16, 10, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (16, 16, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (17, 4, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (17, 25, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (18, 11, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (18, 21, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (18, 9, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (19, 3, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (19, 10, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (19, 24, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (20, 11, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (20, 18, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (21, 29, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (21, 21, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (21, 15, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (22, 21, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (22, 16, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (23, 17, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (23, 7, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (23, 19, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (23, 21, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (23, 18, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (24, 25, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (25, 8, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (26, 12, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (27, 29, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (27, 10, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (28, 25, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (29, 20, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (29, 8, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (29, 10, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (29, 18, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (30, 9, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (30, 7, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (30, 4, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (30, 18, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (31, 12, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (31, 19, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (31, 18, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (32, 2, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (32, 28, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (33, 10, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (33, 13, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (33, 25, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (34, 28, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (34, 27, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (34, 22, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (34, 19, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (34, 1, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (35, 1, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (35, 10, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (35, 15, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (35, 28, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (35, 22, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (36, 2, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (36, 25, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (36, 15, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (36, 5, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (36, 17, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (37, 15, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (37, 3, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (37, 2, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (37, 8, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (38, 23, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (39, 28, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (39, 6, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (39, 19, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (39, 13, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (40, 1, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (40, 4, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (40, 22, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (40, 8, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (40, 5, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (41, 27, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (41, 23, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (41, 26, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (41, 1, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (41, 19, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (42, 2, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (42, 16, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (42, 18, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (43, 9, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (43, 25, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (43, 22, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (43, 23, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (43, 19, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (44, 3, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (44, 23, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (44, 22, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (44, 24, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (44, 5, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (45, 18, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (45, 24, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (45, 12, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (45, 17, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (45, 25, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (46, 2, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (46, 10, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (46, 15, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (47, 13, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (47, 14, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (47, 15, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (48, 22, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (49, 10, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (49, 22, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (49, 28, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (50, 10, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (50, 6, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (50, 17, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (51, 13, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (51, 12, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (52, 19, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (52, 2, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (52, 29, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (52, 10, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (53, 6, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (53, 23, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (53, 9, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (53, 22, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (54, 24, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (54, 21, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (55, 18, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (55, 13, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (55, 3, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (55, 27, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (55, 16, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (56, 22, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (56, 20, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (57, 4, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (58, 1, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (58, 19, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (58, 28, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (58, 25, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (59, 7, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (59, 11, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (60, 20, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (60, 7, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (60, 24, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (60, 14, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (61, 6, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (61, 28, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (61, 3, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (62, 29, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (62, 1, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (63, 15, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (63, 4, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (64, 22, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (65, 16, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (65, 28, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (65, 12, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (65, 10, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (66, 29, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (66, 20, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (66, 8, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (66, 25, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (67, 21, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (68, 20, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (68, 27, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (68, 8, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (69, 2, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (69, 27, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (70, 6, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (70, 28, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (71, 25, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (71, 28, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (71, 2, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (72, 24, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (73, 27, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (73, 12, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (74, 9, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (74, 20, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (74, 27, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (74, 14, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (74, 28, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (75, 3, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (76, 12, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (76, 26, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (76, 10, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (76, 13, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (76, 2, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (77, 4, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (77, 1, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (77, 26, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (77, 7, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (77, 23, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (78, 15, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (78, 9, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (78, 1, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (79, 2, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (79, 25, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (79, 10, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (80, 27, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (80, 5, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (81, 25, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (81, 15, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (81, 7, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (82, 21, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (82, 4, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (82, 18, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (82, 6, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (83, 23, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (83, 4, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (83, 24, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (83, 21, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (83, 28, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (84, 1, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (84, 14, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (84, 24, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (84, 13, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (84, 20, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (85, 5, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (85, 25, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (86, 26, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (86, 14, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (86, 23, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (86, 20, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (87, 25, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (87, 17, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (88, 20, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (88, 7, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (89, 8, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (89, 13, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (90, 19, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (90, 24, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (90, 13, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (90, 29, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (91, 24, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (91, 4, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (92, 1, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (92, 17, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (93, 24, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (93, 27, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (93, 23, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (94, 26, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (94, 19, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (94, 10, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (94, 22, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (94, 18, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (95, 6, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (95, 14, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (95, 5, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (95, 1, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (96, 25, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (96, 11, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (96, 28, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (97, 23, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (98, 1, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (99, 21, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (99, 10, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (99, 17, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (100, 26, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (100, 8, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (100, 15, 8);
