
/* ####################################################### RANDOM INSERTS */


/* ####################################################### technology */

INSERT INTO technology (tech_name) VALUES ('PHP');
INSERT INTO technology (tech_name) VALUES ('JavaScript');
INSERT INTO technology (tech_name) VALUES ('Java');
INSERT INTO technology (tech_name) VALUES ('Python');
INSERT INTO technology (tech_name) VALUES ('Swift');
INSERT INTO technology (tech_name) VALUES ('Ruby');
INSERT INTO technology (tech_name) VALUES ('C++');
INSERT INTO technology (tech_name) VALUES ('C#');
INSERT INTO technology (tech_name) VALUES ('C');
INSERT INTO technology (tech_name) VALUES ('Visual Basic');
INSERT INTO technology (tech_name) VALUES ('Perl');
INSERT INTO technology (tech_name) VALUES ('CSS');
INSERT INTO technology (tech_name) VALUES ('HTML');
INSERT INTO technology (tech_name) VALUES ('Angular');
INSERT INTO technology (tech_name) VALUES ('Django');
INSERT INTO technology (tech_name) VALUES ('Spring');
INSERT INTO technology (tech_name) VALUES ('Yii');
INSERT INTO technology (tech_name) VALUES ('Zend Framework');
INSERT INTO technology (tech_name) VALUES ('Symfony');
INSERT INTO technology (tech_name) VALUES ('ReactJS');
INSERT INTO technology (tech_name) VALUES ('Bootstrap');
INSERT INTO technology (tech_name) VALUES ('Objetive-C');
INSERT INTO technology (tech_name) VALUES ('Pascal');
INSERT INTO technology (tech_name) VALUES ('Go');
INSERT INTO technology (tech_name) VALUES ('Scala');
INSERT INTO technology (tech_name) VALUES ('Rust');
INSERT INTO technology (tech_name) VALUES ('Ruby on rails');
INSERT INTO technology (tech_name) VALUES ('Laravel');
INSERT INTO technology (tech_name) VALUES ('Node JS');

/* ####################################################### search_tech */

INSERT INTO search_tech (id_search, preference, id_technology) VALUES (1, 1, 19);
INSERT INTO search_tech (id_search, preference, id_technology) VALUES (1, 2, 15);
INSERT INTO search_tech (id_search, preference, id_technology) VALUES (1, 3, 11);
INSERT INTO search_tech (id_search, preference, id_technology) VALUES (1, 4, 23);
INSERT INTO search_tech (id_search, preference, id_technology) VALUES (1, 5, 14);

/* ####################################################### developer */

INSERT INTO developer (alias) VALUES ('nullamportarisus');
INSERT INTO developer (alias) VALUES ('cubiliaduisporttitor');
INSERT INTO developer (alias) VALUES ('dictumstleomattis');
INSERT INTO developer (alias) VALUES ('dictumstnequedignissim');
INSERT INTO developer (alias) VALUES ('velitseminterdum');
INSERT INTO developer (alias) VALUES ('nequeconvalliscommodo');
INSERT INTO developer (alias) VALUES ('temportortorvelit');
INSERT INTO developer (alias) VALUES ('ultriciestorquentconsequat');
INSERT INTO developer (alias) VALUES ('massavehicularisus');
INSERT INTO developer (alias) VALUES ('consequatcommodocursus');
INSERT INTO developer (alias) VALUES ('lacusrisusmus');
INSERT INTO developer (alias) VALUES ('doneclectusvenenatis');
INSERT INTO developer (alias) VALUES ('rutrumdignissimnullam');
INSERT INTO developer (alias) VALUES ('egetconguemolestie');
INSERT INTO developer (alias) VALUES ('justolectusnullam');
INSERT INTO developer (alias) VALUES ('rutrumridiculusdignissim');
INSERT INTO developer (alias) VALUES ('erossuscipitlacinia');
INSERT INTO developer (alias) VALUES ('sodalesquampretium');
INSERT INTO developer (alias) VALUES ('integerdignissimporttitor');
INSERT INTO developer (alias) VALUES ('odioultricesporttitor');
INSERT INTO developer (alias) VALUES ('sociisclasshabitant');
INSERT INTO developer (alias) VALUES ('vestibulumcondimentumdictum');
INSERT INTO developer (alias) VALUES ('imperdietviverrased');
INSERT INTO developer (alias) VALUES ('habitantconsequatmetus');
INSERT INTO developer (alias) VALUES ('cubiliaduisfelis');
INSERT INTO developer (alias) VALUES ('nasceturposuerecubilia');
INSERT INTO developer (alias) VALUES ('craslectussem');
INSERT INTO developer (alias) VALUES ('nibhfamesultricies');
INSERT INTO developer (alias) VALUES ('aliquethabitantlacinia');
INSERT INTO developer (alias) VALUES ('tinciduntvestibulumnec');
INSERT INTO developer (alias) VALUES ('volutpatpraesenttristique');
INSERT INTO developer (alias) VALUES ('nibhaptenteu');
INSERT INTO developer (alias) VALUES ('natoquepulvinarnisi');
INSERT INTO developer (alias) VALUES ('nostraduisa');
INSERT INTO developer (alias) VALUES ('namtempushac');
INSERT INTO developer (alias) VALUES ('molestiequisqueduis');
INSERT INTO developer (alias) VALUES ('sodalesinceptosimperdiet');
INSERT INTO developer (alias) VALUES ('nullamhabitanthimenaeos');
INSERT INTO developer (alias) VALUES ('viverrainporttitor');
INSERT INTO developer (alias) VALUES ('pharetramassasuspendisse');
INSERT INTO developer (alias) VALUES ('lectuseudignissim');
INSERT INTO developer (alias) VALUES ('tinciduntcubiliaultrices');
INSERT INTO developer (alias) VALUES ('leoconguedignissim');
INSERT INTO developer (alias) VALUES ('nequetempusaenean');
INSERT INTO developer (alias) VALUES ('magnispotentialiquam');
INSERT INTO developer (alias) VALUES ('ridiculusatincidunt');
INSERT INTO developer (alias) VALUES ('idpretiumporta');
INSERT INTO developer (alias) VALUES ('euismodconubiaimperdiet');
INSERT INTO developer (alias) VALUES ('arcusemperdiam');
INSERT INTO developer (alias) VALUES ('nascetursemperscelerisque');
INSERT INTO developer (alias) VALUES ('morbimagnismontes');
INSERT INTO developer (alias) VALUES ('vulputatenullamhimenaeos');
INSERT INTO developer (alias) VALUES ('antevestibulumscelerisque');
INSERT INTO developer (alias) VALUES ('integerorciconubia');
INSERT INTO developer (alias) VALUES ('muslectusfringilla');
INSERT INTO developer (alias) VALUES ('nuncquamtristique');
INSERT INTO developer (alias) VALUES ('iaculismusnulla');
INSERT INTO developer (alias) VALUES ('hactortorscelerisque');
INSERT INTO developer (alias) VALUES ('dictumvelnascetur');
INSERT INTO developer (alias) VALUES ('phasellussempervehicula');
INSERT INTO developer (alias) VALUES ('famesdiamiaculis');
INSERT INTO developer (alias) VALUES ('tacititempusquisque');
INSERT INTO developer (alias) VALUES ('sociosqutempordis');
INSERT INTO developer (alias) VALUES ('liberoaliquamblandit');
INSERT INTO developer (alias) VALUES ('mollisnonsed');
INSERT INTO developer (alias) VALUES ('velitsodaleslaoreet');
INSERT INTO developer (alias) VALUES ('fringillaurnadignissim');
INSERT INTO developer (alias) VALUES ('etviverraplatea');
INSERT INTO developer (alias) VALUES ('semdiammassa');
INSERT INTO developer (alias) VALUES ('laciniafringillaposuere');
INSERT INTO developer (alias) VALUES ('duissuscipitblandit');
INSERT INTO developer (alias) VALUES ('sociosqufaucibusmorbi');
INSERT INTO developer (alias) VALUES ('himenaeoscumluctus');
INSERT INTO developer (alias) VALUES ('bibendumpharetratristique');
INSERT INTO developer (alias) VALUES ('auctorlaciniacommodo');
INSERT INTO developer (alias) VALUES ('variusconsequatnostra');
INSERT INTO developer (alias) VALUES ('fringillacuraesuspendisse');
INSERT INTO developer (alias) VALUES ('penatibussuspendissesapien');
INSERT INTO developer (alias) VALUES ('bibendummusvelit');
INSERT INTO developer (alias) VALUES ('temporidpharetra');
INSERT INTO developer (alias) VALUES ('himenaeosestplacerat');
INSERT INTO developer (alias) VALUES ('conubialeonec');
INSERT INTO developer (alias) VALUES ('erosvivamusquisque');
INSERT INTO developer (alias) VALUES ('dapibusrisusaliquet');
INSERT INTO developer (alias) VALUES ('primissagittisrisus');
INSERT INTO developer (alias) VALUES ('nullavehiculamassa');
INSERT INTO developer (alias) VALUES ('mattissodalesfacilisis');
INSERT INTO developer (alias) VALUES ('lobortisnequeplacerat');
INSERT INTO developer (alias) VALUES ('habitasseligulabibendum');
INSERT INTO developer (alias) VALUES ('portabibendumante');
INSERT INTO developer (alias) VALUES ('semhimenaeoseleifend');
INSERT INTO developer (alias) VALUES ('inaliquetpharetra');
INSERT INTO developer (alias) VALUES ('viverradapibusvitae');
INSERT INTO developer (alias) VALUES ('nullaelitquis');
INSERT INTO developer (alias) VALUES ('lacusauguehendrerit');
INSERT INTO developer (alias) VALUES ('tristiquetellusmalesuada');
INSERT INTO developer (alias) VALUES ('sodalesposuerevolutpat');
INSERT INTO developer (alias) VALUES ('vivamusportapharetra');
INSERT INTO developer (alias) VALUES ('nullamgravidamontes');
INSERT INTO developer (alias) VALUES ('pretiumhactaciti');

/* ####################################################### developer_tech */

INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (1, 14, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (1, 8, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (1, 21, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (2, 6, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (3, 2, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (3, 28, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (4, 15, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (4, 9, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (5, 24, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (6, 2, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (6, 6, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (6, 28, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (6, 4, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (6, 12, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (7, 24, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (7, 27, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (7, 17, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (8, 17, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (8, 7, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (8, 14, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (8, 18, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (8, 6, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (8, 26, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (8, 23, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (8, 13, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (8, 15, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (9, 5, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (9, 2, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (9, 1, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (10, 1, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (10, 11, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (10, 24, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (10, 15, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (10, 10, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (10, 12, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (10, 14, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (10, 23, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (11, 4, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (11, 1, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (11, 26, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (11, 15, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (11, 23, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (11, 24, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (11, 17, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (11, 11, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (11, 5, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (11, 28, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (12, 27, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (13, 12, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (13, 6, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (13, 22, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (13, 10, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (13, 13, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (13, 29, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (13, 11, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (14, 11, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (14, 1, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (14, 14, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (14, 10, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (14, 29, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (14, 3, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (14, 7, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (14, 5, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (14, 4, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (14, 8, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (15, 25, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (15, 16, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (15, 28, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (15, 9, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (15, 11, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (16, 7, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (16, 23, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (16, 9, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (16, 2, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (16, 20, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (16, 28, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (16, 17, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (16, 15, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (16, 19, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (17, 29, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (18, 8, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (18, 27, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (18, 13, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (18, 16, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (19, 14, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (19, 7, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (19, 25, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (19, 2, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (19, 6, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (19, 8, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (19, 18, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (20, 8, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (20, 23, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (20, 5, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (21, 26, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (21, 14, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (21, 19, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (21, 27, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (21, 1, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (21, 28, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (22, 14, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (22, 2, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (22, 9, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (22, 28, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (22, 6, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (22, 4, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (22, 29, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (22, 11, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (22, 17, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (23, 12, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (23, 26, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (23, 15, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (23, 5, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (23, 3, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (23, 22, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (23, 23, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (23, 24, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (23, 19, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (23, 17, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (24, 4, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (24, 29, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (24, 7, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (24, 5, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (25, 7, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (26, 29, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (27, 26, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (27, 14, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (27, 11, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (27, 21, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (27, 27, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (27, 10, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (27, 6, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (28, 8, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (28, 18, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (28, 12, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (28, 26, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (28, 10, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (28, 25, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (29, 8, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (29, 28, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (29, 27, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (29, 29, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (29, 5, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (29, 21, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (30, 22, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (30, 18, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (30, 20, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (30, 5, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (30, 1, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (30, 13, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (31, 14, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (31, 2, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (31, 22, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (31, 4, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (31, 13, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (31, 15, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (31, 7, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (31, 18, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (32, 2, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (32, 29, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (32, 26, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (32, 17, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (32, 4, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (33, 11, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (33, 3, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (33, 23, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (33, 19, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (33, 27, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (34, 28, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (34, 12, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (34, 8, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (34, 29, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (34, 7, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (34, 13, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (34, 3, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (34, 23, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (35, 21, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (35, 13, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (35, 20, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (35, 9, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (36, 25, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (36, 14, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (36, 18, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (36, 27, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (36, 2, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (36, 22, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (36, 28, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (36, 29, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (36, 15, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (37, 4, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (37, 14, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (37, 17, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (37, 29, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (37, 12, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (38, 28, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (38, 20, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (38, 21, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (39, 2, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (39, 16, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (39, 18, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (39, 25, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (39, 12, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (39, 10, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (39, 15, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (39, 3, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (39, 22, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (39, 5, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (40, 29, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (41, 23, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (41, 4, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (41, 15, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (41, 29, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (41, 16, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (41, 7, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (41, 9, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (41, 27, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (41, 5, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (42, 29, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (42, 15, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (42, 19, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (43, 21, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (43, 23, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (43, 15, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (43, 26, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (43, 1, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (43, 16, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (44, 9, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (44, 8, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (44, 25, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (45, 13, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (45, 11, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (46, 13, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (46, 4, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (46, 3, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (47, 8, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (47, 9, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (47, 25, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (48, 26, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (48, 11, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (48, 9, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (48, 19, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (48, 12, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (48, 5, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (49, 25, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (49, 21, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (49, 22, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (49, 24, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (49, 9, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (49, 13, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (49, 16, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (49, 8, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (50, 17, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (51, 18, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (51, 5, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (51, 28, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (52, 9, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (52, 24, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (52, 15, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (52, 1, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (52, 19, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (52, 8, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (53, 3, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (53, 12, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (53, 23, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (53, 16, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (54, 22, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (54, 24, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (54, 14, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (54, 17, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (54, 5, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (55, 4, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (55, 10, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (55, 7, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (56, 13, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (56, 10, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (56, 15, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (56, 25, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (56, 19, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (56, 7, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (56, 28, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (56, 4, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (57, 4, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (57, 8, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (57, 9, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (57, 14, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (57, 18, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (57, 15, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (57, 5, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (58, 1, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (58, 28, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (58, 18, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (58, 21, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (58, 3, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (58, 26, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (58, 12, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (59, 4, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (59, 18, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (59, 21, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (59, 6, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (59, 29, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (59, 2, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (59, 28, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (59, 14, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (59, 13, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (59, 7, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (60, 23, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (60, 3, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (60, 6, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (60, 20, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (60, 1, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (60, 28, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (60, 19, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (60, 12, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (60, 16, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (60, 14, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (61, 1, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (61, 7, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (61, 12, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (62, 11, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (62, 19, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (62, 5, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (62, 9, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (62, 4, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (62, 15, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (62, 29, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (62, 26, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (62, 7, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (62, 16, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (63, 8, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (63, 6, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (63, 4, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (63, 7, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (64, 5, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (64, 17, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (64, 16, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (64, 4, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (64, 21, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (64, 18, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (64, 14, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (64, 23, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (64, 29, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (64, 25, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (65, 22, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (65, 28, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (65, 14, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (65, 12, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (65, 4, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (65, 17, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (65, 21, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (65, 25, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (65, 3, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (65, 29, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (66, 3, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (66, 7, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (66, 19, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (66, 29, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (66, 4, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (66, 27, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (66, 17, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (66, 1, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (66, 22, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (67, 27, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (67, 8, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (67, 1, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (68, 11, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (68, 18, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (68, 8, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (68, 3, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (68, 28, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (68, 15, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (68, 19, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (69, 24, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (69, 21, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (69, 12, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (69, 28, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (69, 1, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (69, 29, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (69, 3, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (69, 22, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (69, 2, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (69, 4, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (70, 19, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (70, 3, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (70, 16, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (70, 25, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (71, 9, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (71, 14, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (71, 24, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (71, 10, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (71, 13, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (71, 17, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (71, 6, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (72, 6, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (72, 11, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (72, 22, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (72, 5, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (72, 14, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (72, 4, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (72, 13, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (73, 17, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (73, 18, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (73, 4, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (73, 25, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (73, 19, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (73, 24, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (73, 2, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (74, 28, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (74, 17, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (74, 12, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (74, 27, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (74, 20, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (74, 15, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (74, 4, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (74, 5, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (74, 14, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (75, 19, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (75, 18, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (76, 23, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (76, 3, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (76, 24, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (76, 20, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (76, 11, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (76, 5, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (76, 19, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (77, 7, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (77, 3, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (78, 28, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (78, 17, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (78, 20, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (78, 9, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (78, 22, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (79, 14, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (80, 12, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (80, 4, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (80, 23, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (80, 28, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (81, 21, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (81, 6, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (81, 12, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (81, 24, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (81, 17, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (82, 17, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (82, 21, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (82, 7, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (82, 13, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (82, 1, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (83, 12, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (83, 24, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (83, 28, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (83, 7, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (83, 20, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (83, 5, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (83, 14, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (83, 1, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (84, 20, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (84, 7, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (84, 21, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (84, 6, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (85, 13, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (85, 2, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (85, 19, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (85, 23, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (85, 18, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (85, 3, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (86, 23, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (86, 21, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (86, 6, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (86, 14, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (86, 2, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (86, 28, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (86, 26, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (86, 3, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (86, 13, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (86, 4, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (87, 11, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (87, 14, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (87, 13, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (87, 18, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (87, 5, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (87, 28, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (88, 24, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (88, 1, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (88, 27, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (88, 18, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (88, 9, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (88, 7, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (89, 16, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (89, 10, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (89, 22, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (89, 27, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (89, 1, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (89, 20, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (89, 29, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (89, 4, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (89, 8, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (89, 17, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (90, 29, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (90, 4, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (90, 5, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (90, 7, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (90, 6, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (90, 19, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (90, 18, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (91, 10, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (91, 23, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (91, 22, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (91, 14, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (91, 26, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (92, 27, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (92, 1, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (92, 9, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (92, 2, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (92, 18, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (92, 7, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (92, 15, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (92, 14, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (92, 8, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (93, 22, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (93, 19, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (93, 13, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (93, 11, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (93, 2, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (93, 26, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (93, 10, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (93, 7, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (93, 3, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (93, 23, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (94, 14, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (94, 25, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (94, 23, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (94, 1, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (94, 26, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (94, 21, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (94, 7, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (94, 8, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (95, 3, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (95, 16, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (95, 27, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (95, 18, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (95, 24, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (95, 22, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (95, 1, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (95, 21, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (95, 2, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (95, 19, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (96, 9, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (96, 25, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (96, 13, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (96, 21, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (97, 8, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (97, 17, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (97, 6, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (97, 29, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (97, 12, 2);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (98, 16, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (98, 24, 7);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (98, 21, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (98, 13, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (98, 27, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (98, 11, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (99, 23, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (99, 12, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (99, 3, 8);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (99, 28, 3);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (99, 22, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (99, 26, 9);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (99, 15, 5);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (99, 19, 1);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (99, 18, 6);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (100, 26, 10);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (100, 14, 4);
INSERT INTO developer_tech (id_developer, id_technology, level) VALUES (100, 17, 2);
