#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User


# config/packages/easy_admin.yaml
easy_admin:
    entities:
        # change the following to the namespaces of your own entities
        User:
          class:  App\Entity\User
          form: 
            fields: 
              - id
              - type
              - user
              - pass
              - auth